# Generated by Django 2.2.1 on 2019-05-27 03:20

import datetime
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=300)),
                ('logo', sorl.thumbnail.fields.ImageField(default='', upload_to='img/assets/')),
                ('favicon', sorl.thumbnail.fields.ImageField(default='', upload_to='img/assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('summary', models.CharField(default='', max_length=100)),
                ('image', sorl.thumbnail.fields.ImageField(default='', upload_to='img/projects/')),
                ('badges', models.TextField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
