# Generated by Django 2.2.1 on 2019-05-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
