# Generated by Django 2.2.2 on 2019-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190529_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
