# Generated by Django 2.2.2 on 2019-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
