# Generated by Django 2.2.1 on 2019-05-25 01:14

import datetime
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('preview', models.CharField(default='', max_length=255)),
                ('latex_support', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='articles/%Y/%m/%d')),
                ('content', models.TextField(default='', max_length=20000)),
                ('modified', models.DateField(default=datetime.date.today)),
                ('published', models.DateField(default=datetime.date.today)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
