# Generated by Django 2.2.1 on 2019-05-25 01:43

import datetime
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('summary', models.CharField(default='', max_length=100)),
                ('image', sorl.thumbnail.fields.ImageField(default='', upload_to='img/projects/')),
                ('badges', models.TextField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='preview',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
