# Generated by Django 2.2.1 on 2019-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190525_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
