# Generated by Django 2.2.1 on 2019-05-27 03:06

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=300)),
                ('logo', sorl.thumbnail.fields.ImageField(default='', upload_to='img/assets/')),
                ('favicon', sorl.thumbnail.fields.ImageField(default='', upload_to='img/assets/')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=350),
        ),
    ]
