# Generated by Django 2.2.1 on 2019-05-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190529_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
