# Generated by Django 2.2.2 on 2019-06-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190529_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
